const cases=[
{id:"DS-2841",name:"Olivia Rhye",ini:"OR",avatar:"",descriptor:"NORTHSTAR*GOODS",amount:"$248.00",issue:"Delivery delay",signal:"Delivery SLA exceeded by 3 days",age:"12 min ago",risk:"High",action:"Send delivery update",status:"Needs review",evidence:["Order #NS-90821 has not shipped","Promised delivery was Sep 22","Customer contacted support 18 minutes ago"]},
{id:"DS-2839",name:"Phoenix Baker",ini:"PB",avatar:"av-peach",descriptor:"CLOUDNINE*MONTHLY",amount:"$39.00",issue:"Billing confusion",signal:"Subscription amount changed",age:"34 min ago",risk:"High",action:"Send updated invoice",status:"Approval needed",evidence:["Monthly amount changed from $29 to $39","Subscription updated Sep 21","No updated invoice delivery recorded"]},
{id:"DS-2837",name:"Lana Steiner",ini:"LS",avatar:"av-mint",descriptor:"ACME*STUDIO",amount:"$129.00",issue:"Transaction recognition",signal:"Receipt delivery failed",age:"1 hr ago",risk:"Medium",action:"Resend receipt",status:"Monitoring",evidence:["Receipt email bounced at 10:42 AM","Merchant descriptor is ACME*STUDIO","No prior disputes on this account"]},
{id:"DS-2834",name:"Demi Wilkinson",ini:"DW",avatar:"av-blue",descriptor:"PEAK*OUTDOORS",amount:"$485.00",issue:"Duplicate-looking payment",signal:"Two charges 42 seconds apart",age:"2 hrs ago",risk:"High",action:"Investigate possible duplicate",status:"Needs review",evidence:["Two payments of $485.00 within 42 seconds","Different payment session IDs","Both orders show fulfillment in progress"]},
{id:"DS-2832",name:"Candice Wu",ini:"CW",avatar:"av-rose",descriptor:"FORM*WELLNESS",amount:"$86.00",issue:"Refund delay",signal:"Refund pending for 6 days",age:"3 hrs ago",risk:"Medium",action:"Send refund status",status:"Monitoring",evidence:["Refund requested Sep 19","Refund remains in processing","Customer contacted support once"]},
{id:"DS-2828",name:"Natali Craig",ini:"NC",avatar:"av-sand",descriptor:"VERDE*MARKET",amount:"$1,840.00",issue:"Unusual transaction",signal:"New device · high amount",age:"4 hrs ago",risk:"High",action:"Flag for human review",status:"Approval needed",evidence:["First transaction on this device","Amount is 4.8× customer average","Location differs from prior activity"]}];
let active="all", selected=null;
const rows=document.querySelector("#rows"), search=document.querySelector("#search"), shown=document.querySelector("#shown");
function render(){let term=search.value.toLowerCase();let visible=cases.filter(c=>(active==="all"||(active==="review"&&c.status==="Needs review")||c.risk===active)&&`${c.name} ${c.id} ${c.issue} ${c.descriptor}`.toLowerCase().includes(term)).slice(0,5);shown.textContent=visible.length;rows.innerHTML=visible.length?visible.map(c=>`<tr data-id="${c.id}"><td><div class="customer"><div class="avatar ${c.avatar}">${c.ini}</div><div><b>${c.name}</b><small>${c.id} · ${c.descriptor} · ${c.amount}</small></div></div></td><td><span class="signal">${c.issue}</span><small class="subsignal">${c.signal}</small></td><td><span class="risk ${c.risk==='Medium'?'risk-medium':''}"><i></i>${c.risk}</span></td><td class="action-col">${c.action}</td><td><span class="status ${c.status.toLowerCase().replaceAll(' ','-')}">${c.status}</span></td><td><button class="row-open" aria-label="Open ${c.id}">↗</button></td></tr>`).join(""):`<tr><td colspan="6"><div class="empty">No cases match this search.</div></td></tr>`;rows.querySelectorAll("tr[data-id]").forEach(row=>row.addEventListener("click",()=>openCase(row.dataset.id)));}
function openCase(id){selected=cases.find(c=>c.id===id);document.querySelector("#caseid").textContent=selected.id;document.querySelector("#issue").textContent=selected.issue;document.querySelector("#person").innerHTML=`<div class="avatar ${selected.avatar}">${selected.ini}</div><span><b>${selected.name}</b><small>${selected.descriptor} · ${selected.amount}</small></span><span class="risk ${selected.risk==='Medium'?'risk-medium':''}"><i></i>${selected.risk} risk</span>`;document.querySelector("#signal").textContent=`${selected.signal}. This is an early warning signal after payment, before a dispute has been filed.`;const evidenceList=document.querySelector("#evidence");evidenceList.replaceChildren();selected.evidence.forEach((value,index)=>{const item=document.createElement("li");item.className="evidence-item";const text=document.createElement("span");text.textContent=value;const meta=document.createElement("small");meta.textContent=`${selected.id}-E${index+1} · Illustrative scenario · Timestamp unavailable`;const badge=document.createElement("b");badge.className="evidence-demo";badge.textContent="DEMO";item.append(text,meta,badge);evidenceList.append(item)});document.querySelector("#action").textContent=`${selected.action}. Deterministic policy checks apply before any customer-facing action.`;document.querySelector("#modal").hidden=false;}
function close(){document.querySelector("#modal").hidden=true}function notify(msg){let t=document.querySelector("#toast");t.textContent="✓  "+msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2800)}
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelector(".tab.current")?.classList.remove("current");b.classList.add("current");active=b.dataset.filter;render()}));search.addEventListener("input",render);document.querySelector("#filter").addEventListener("click",()=>{active=active==="review"?"all":"review";document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("current",b.dataset.filter===active));render()});document.querySelector("#close").addEventListener("click",close);document.querySelector("#modal").addEventListener("click",e=>{if(e.target.id==="modal")close()});document.querySelector("#dismiss").addEventListener("click",()=>{if(selected)selected.status="Monitoring";close();render();notify("Case dismissed · decision added to audit trail")});document.querySelector("#approve").addEventListener("click",()=>{if(selected)selected.status="Monitoring";close();render();notify("Action approved · now monitoring outcome")});document.querySelector("#export").addEventListener("click",()=>{let csv="case_id,customer,issue,risk,status\n"+cases.map(c=>`${c.id},${c.name},${c.issue},${c.risk},${c.status}`).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="disputeshield-cases.csv";a.click();URL.revokeObjectURL(a.href)});render();
